blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://github.com/nholuongut/argo-events/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/nholuongut/argo-events/discussions/new
    about: Ask a question or start a discussion about Argo Events
  - name: My Github Repositories
    url: https://github.com/nholuongut/argo-events/
    about: Maybe chatting with the community can help
